name: Publish Implementation Guide

on:
  push:
    branches:
      - main
      - uat

jobs:
  publish-ig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Request IG build
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          API_KEY: ${{ github.ref_name == 'main' && secrets.API_KEY || secrets.API_KEY_UAT }}
          BUILDER_URL: ${{ github.ref_name == 'main' && 'https://fhir-ig-builder.api.digital.health.nz/v1/build' || 'https://fhir-ig-builder.api-uat.digital.health.nz/v1/build' }}
        run: |
          curl --fail-with-body --request POST "$BUILDER_URL" \
            --header "Content-Type: application/json" \
            --header "x-api-key: $API_KEY" \
            --data "{\"gitBranch\":\"$BRANCH_NAME\",\"igSourceGitUrl\":\"https://github.com/${GITHUB_REPOSITORY}.git\"}"
